name: Build and Publish Lua Docs

on:
  push:
    branches: ["main"]
    paths:
      - "api/lua/**"
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  SSH_DEPLOY_KEY: ${{ secrets.DOCS_DEPLOY_KEY_LUA }}

jobs:
  build:
    runs-on: ubuntu-24.04
    name: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Checkout lcat
        uses: actions/checkout@v4
        with:
          repository: Ottatop/lcat
          path: ./lcat
      - name: Get Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Cache stuff
        uses: Swatinem/rust-cache@v2
      - name: Generate docs
        run: |
          cd ./lcat
          cargo run -- --dir "../api/lua" --base-url "/lua-reference/main/"
      - name: Push files
        uses: cpina/github-action-push-to-another-repository@v1.7.2
        with:
          source-directory: "./lcat/lcat_out"
          destination-github-username: "pinnacle-comp"
          destination-repository-name: "lua-reference"
          target-branch: main
          target-directory: main
